<a href="https://colab.research.google.com/github/ajaysaikiran2208/MLCONCEPTS/blob/main/Categorical_Variables_and_One_Hot_Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Categorical Variables and One Hot Encoding**

In [36]:
!pip install catboost

     |████████████████████████████████| 67.3MB 58kB/s 


In [37]:
# importing libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import missingno as msno

import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier
from sklearn.ensemble import ExtraTreesClassifier
from lightgbm import LGBMClassifier
from sklearn.ensemble import VotingClassifier

import folium
from folium.plugins import HeatMap
import plotly.express as px

plt.style.use('fivethirtyeight')
%matplotlib inline
pd.set_option('display.max_columns', 32)

In [ ]:
df = pd.read_csv("/content/homeprices.csv")
df

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

Using pandas to create dummy variables

In [ ]:
dummies = pd.get_dummies(df.town)  #It will get dummy variables of the given Column
dummies

monroe township  robinsville  west windsor
0                 1            0             0
1                 1            0             0
2                 1            0             0
3                 1            0             0
4                 1            0             0
5                 0            0             1
6                 0            0             1
7                 0            0             1
8                 0            0             1
9                 0            1             0
10                0            1             0
11                0            1             0
12                0            1             0

In [ ]:
merged = pd.concat([df,dummies],axis='columns')  #Concatinating dummy variables with the original dataset
merged

town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000                1            0             0
1   monroe township  3000  565000                1            0             0
2   monroe township  3200  610000                1            0             0
3   monroe township  3600  680000                1            0             0
4   monroe township  4000  725000                1            0             0
5      west windsor  2600  585000                0            0             1
6      west windsor  2800  615000                0            0             1
7      west windsor  3300  650000                0            0             1
8      west windsor  3600  710000                0            0             1
9       robinsville  2600  575000                0            1             0
10      robinsville  2900  600000                0            1             0
11      robinsville  3100  620000                0            1             0
12      robinsville  3600  695000                0            1             0

In [ ]:
final = merged.drop(['town'], axis='columns') # Since Dummy columns has town we are droping town
final

area   price  monroe township  robinsville  west windsor
0   2600  550000                1            0             0
1   3000  565000                1            0             0
2   3200  610000                1            0             0
3   3600  680000                1            0             0
4   4000  725000                1            0             0
5   2600  585000                0            0             1
6   2800  615000                0            0             1
7   3300  650000                0            0             1
8   3600  710000                0            0             1
9   2600  575000                0            1             0
10  2900  600000                0            1             0
11  3100  620000                0            1             0
12  3600  695000                0            1             0

**Dummy Variable Trap**


When you can derive one variable from other variables, they are known to be multi-colinear. Here if you know values of california and georgia then you can easily infer value of new jersey state, i.e. california=0 and georgia=0. There for these state variables are called to be multi-colinear. In this situation linear regression won't work as expected. Hence you need to drop one column.

NOTE: sklearn library takes care of dummy variable trap hence even if you don't drop one of the state columns it is going to work, however we should make a habit of taking care of dummy variable trap ourselves just in case library that you are using is not handling this for you

In [ ]:
final = final.drop(['west windsor'], axis='columns') #Doing this to overcome dummy variable trap
final

area   price  monroe township  robinsville
0   2600  550000                1            0
1   3000  565000                1            0
2   3200  610000                1            0
3   3600  680000                1            0
4   4000  725000                1            0
5   2600  585000                0            0
6   2800  615000                0            0
7   3300  650000                0            0
8   3600  710000                0            0
9   2600  575000                0            1
10  2900  600000                0            1
11  3100  620000                0            1
12  3600  695000                0            1

In [ ]:
X = final.drop('price', axis='columns') #Since Price is dependent we are making it as "Y"
X

area  monroe township  robinsville
0   2600                1            0
1   3000                1            0
2   3200                1            0
3   3600                1            0
4   4000                1            0
5   2600                0            0
6   2800                0            0
7   3300                0            0
8   3600                0            0
9   2600                0            1
10  2900                0            1
11  3100                0            1
12  3600                0            1

In [31]:
y = final.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [ ]:
model.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
model.predict(X) # 2600 sqr ft home in new jersey

array([539709.7398409 , 590468.71640508, 615848.20468716, 666607.18125134,
       717366.15781551, 579723.71533005, 605103.20361213, 668551.92431735,
       706621.15674048, 565396.15136531, 603465.38378844, 628844.87207052,
       692293.59277574])

In [ ]:
model.score(X,y)

0.9573929037221873

In [ ]:
model.predict([[3400,0,0]]) # 3400 sqr ft home in west windsor

array([681241.66845839])

In [ ]:

model.predict([[2800,0,1]]) # 2800 sqr ft home in robbinsville

array([590775.63964739])

Using sklearn OneHotEncoder

First step is to use label encoder to convert town names into numbers

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [32]:
dfle = df
dfle.town = le.fit_transform(dfle.town)
dfle

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [34]:
le.fit_transform(dfle.town)

array([0, 0, 0, 0, 0, 2, 2, 2, 2, 1, 1, 1, 1])

In [ ]:

X = dfle[['town','area']].values

In [ ]:
X

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]])

In [ ]:
y = dfle.price.values
y

array([550000, 565000, 610000, 680000, 725000, 585000, 615000, 650000,
       710000, 575000, 600000, 620000, 695000])

Now use one hot encoder to create dummy variables for each of the town

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([('town', OneHotEncoder(), [0])], remainder = 'passthrough')

In [ ]:
X = ct.fit_transform(X)
X

array([[1.0e+00, 0.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.0e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.2e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.9e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.1e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.6e+03]])

In [ ]:
X = X[:,1:]

In [ ]:

X

array([[0.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 3.0e+03],
       [0.0e+00, 0.0e+00, 3.2e+03],
       [0.0e+00, 0.0e+00, 3.6e+03],
       [0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 1.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 2.9e+03],
       [1.0e+00, 0.0e+00, 3.1e+03],
       [1.0e+00, 0.0e+00, 3.6e+03]])

In [ ]:
model.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
model.predict([[0,1,3400]]) # 3400 sqr ft home in west windsor

array([681241.6684584])

In [ ]:
model.predict([[1,0,2800]]) # 2800 sqr ft home in robbinsville

array([590775.63964739])

## KNN

In [38]:
knn = KNeighborsClassifier()
knn.fit(X,y)


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [42]:
knn.predict([[0,1,3600]])

array([650000])

## EXERCISE TO SOLVE

OBJECTIVE:

To predict prices of car based on car model, age, mileage

In [68]:
car_pred=pd.read_csv("/content/CARSPREDICT.csv")
car_pred

Car_Model  Mileage  Sell_Price  Age(yrs)
0                  BMW X5    69000       18000         6
1                  BMW X5    35000       34000         3
2                  BMW X5    57000       26100         5
3                  BMW X5    22500       40000         2
4                  BMW X5    46000       31500         4
5                 Audi A5    59000       29400         5
6                 Audi A5    52000       32000         5
7                 Audi A5    72000       19300         6
8                 Audi A5    91000       12000         8
9   Mercedez Benz C class    67000       22000         6
10  Mercedez Benz C class    83000       20000         7
11  Mercedez Benz C class    79000       21000         7
12  Mercedez Benz C class    59000       33000         5

In [69]:
dummies = pd.get_dummies(car_pred.Car_Model)
dummies

Audi A5  BMW X5  Mercedez Benz C class
0         0       1                      0
1         0       1                      0
2         0       1                      0
3         0       1                      0
4         0       1                      0
5         1       0                      0
6         1       0                      0
7         1       0                      0
8         1       0                      0
9         0       0                      1
10        0       0                      1
11        0       0                      1
12        0       0                      1

In [70]:
merged = pd.concat([car_pred,dummies],axis='columns')
merged

Car_Model  Mileage  Sell_Price  Age(yrs)  Audi A5  BMW X5  \
0                  BMW X5    69000       18000         6        0       1   
1                  BMW X5    35000       34000         3        0       1   
2                  BMW X5    57000       26100         5        0       1   
3                  BMW X5    22500       40000         2        0       1   
4                  BMW X5    46000       31500         4        0       1   
5                 Audi A5    59000       29400         5        1       0   
6                 Audi A5    52000       32000         5        1       0   
7                 Audi A5    72000       19300         6        1       0   
8                 Audi A5    91000       12000         8        1       0   
9   Mercedez Benz C class    67000       22000         6        0       0   
10  Mercedez Benz C class    83000       20000         7        0       0   
11  Mercedez Benz C class    79000       21000         7        0       0   
12  Mercedez Benz C class    59000       33000         5        0       0   

    Mercedez Benz C class  
0                       0  
1                       0  
2                       0  
3                       0  
4                       0  
5                       0  
6                       0  
7                       0  
8                       0  
9                       1  
10                      1  
11                      1  
12                      1

In [71]:
final = merged.drop(['Car_Model'], axis='columns')
final

Mileage  Sell_Price  Age(yrs)  Audi A5  BMW X5  Mercedez Benz C class
0     69000       18000         6        0       1                      0
1     35000       34000         3        0       1                      0
2     57000       26100         5        0       1                      0
3     22500       40000         2        0       1                      0
4     46000       31500         4        0       1                      0
5     59000       29400         5        1       0                      0
6     52000       32000         5        1       0                      0
7     72000       19300         6        1       0                      0
8     91000       12000         8        1       0                      0
9     67000       22000         6        0       0                      1
10    83000       20000         7        0       0                      1
11    79000       21000         7        0       0                      1
12    59000       33000         5        0       0                      1

In [72]:
final = final.drop(['Audi A5'], axis='columns')
final

Mileage  Sell_Price  Age(yrs)  BMW X5  Mercedez Benz C class
0     69000       18000         6       1                      0
1     35000       34000         3       1                      0
2     57000       26100         5       1                      0
3     22500       40000         2       1                      0
4     46000       31500         4       1                      0
5     59000       29400         5       0                      0
6     52000       32000         5       0                      0
7     72000       19300         6       0                      0
8     91000       12000         8       0                      0
9     67000       22000         6       0                      1
10    83000       20000         7       0                      1
11    79000       21000         7       0                      1
12    59000       33000         5       0                      1

In [73]:
X = final.drop('Sell_Price', axis='columns')
X

Mileage  Age(yrs)  BMW X5  Mercedez Benz C class
0     69000         6       1                      0
1     35000         3       1                      0
2     57000         5       1                      0
3     22500         2       1                      0
4     46000         4       1                      0
5     59000         5       0                      0
6     52000         5       0                      0
7     72000         6       0                      0
8     91000         8       0                      0
9     67000         6       0                      1
10    83000         7       0                      1
11    79000         7       0                      1
12    59000         5       0                      1

In [74]:
y = final.Sell_Price

In [75]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [76]:
model.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [77]:
model.predict(X)

array([18705.2723644 , 35286.78445645, 24479.19112468, 41245.76426391,
       29882.98779056, 28023.6135243 , 30614.46818502, 21879.57266964,
       12182.34562104, 26183.72387884, 18929.31674102, 20409.80511857,
       30477.15426156])

In [78]:
model.score(X,y)

0.9417050937281083

In [86]:
model.predict([[45000,6,0,0]])

array([31872.86921813])

In [82]:
knn = KNeighborsClassifier()
knn.fit(X,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [88]:
model.predict([[20000,2,0,0]])

array([46455.73608828])