<a href="https://colab.research.google.com/github/ajaysaikiran2208/MLCONCEPTS/blob/main/Gradient_Descent_Implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
dataset=[[2,6],[3,6],[5,10]]

In [2]:
x=[k[0] for k in dataset]

In [3]:
y=[k[1] for k in dataset]

In [5]:
#Paramters
b0,b1=0,1.0
#Hyperparameters
lr=0.001
max_iterations=10000
error=[]

In [21]:
for epoch in range(max_iterations):
    cost_b0, cost_b1 = 0,0

    for i in range(len(x)):
        y_pred = b0+b1*x[i]
        cost_b0 += y[i] - y_pred
        cost_b1 += (y[i] - y_pred)*x[i]

    b0 = b0 + lr * cost_b0
    b1 = b1 + lr * cost_b1



In [22]:
b0=b0+lr*cost_b0
b1=b0+lr*cost_b1

In [23]:
b0,b1

(2.5061113000157227, 2.506105322725492)

In [25]:
X_new=10
y_new=b0+b1*X_new

In [26]:
y_new

27.56716452727064

In [20]:
#Linear regression with scikitlearn

In [29]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [30]:
X=[[0,1],[5,1],[15,2],[25,5],[35,11],[45,35],[60,35]]
y=[4,5,20,32,22,38,43]
X=np.array(X)
y=np.array(y)

In [31]:
model=LinearRegression()
model.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [32]:
model.intercept_

5.758929293746451

In [35]:
model.coef_

array([ 0.7161779 , -0.09783796])

In [37]:
model.predict([[25,5]])

array([23.17418696])

In [38]:
model.predict(X)

array([ 5.66109134,  9.24198083, 16.30592185, 23.17418696, 29.74893819,
       34.56260618, 45.30527465])

In [39]:
model.score(X,y)

0.8646360707222717